# Generated by Django 4.2.4 on 2023-09-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eskak.entry')),
            ],
        ),
    ]
